spring:
  cloud:
    sentinel:
      filter:
        enabled: true
      transport:
        port: 8719
        #指定sentinel控制台的地址
        dashboard: 127.0.0.1:8086
      eager: true
#Ribbon配置
ribbon:
  #请求连接的超时时间
  ConnectTimeout: 5000
  #请求处理/响应的超时时间
  ReadTimeout: 5000
  #对所有操作请求都进行重试
  OkToRetryOnAllOperations: true
  #切换实例的重试次数
  MaxAutoRetriesNextServer: 1
  #当前实例的重试次数
  MaxAutoRetries: 1
#Sentinel端点配置
management:
  endpoints:
    web:
      exposure:
        include: '*'